### ISSUE TITLE
NullReferenceException for missing parenthesis around argument list of an arrow function

### ISSUE THREAD

**Issue by stefanloerwald** [xoofx/NUglify#92]
The following code snippet fails minification with the exception below:
```js
Promise.then(async arg => { return 0; });
```
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at NUglify.JavaScript.JSParser.ParseArrowFunction(AstNode parameters)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseFunctionBody(BlockStatement body)
   at NUglify.JavaScript.JSParser.ParseFunction(FunctionType functionType, SourceContext fncCtx)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpression(AstNode leftHandSide, Boolean single, Boolean bCanAssign, JSToken inToken)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext, CodeSettings settings)
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)
   at NUglify.Uglify.Js(String source, CodeSettings codeSettings)
  
```

It seems to be the combination of async and missing parenthesis, because these are non-throwing versions:
```js
Promise.then(async (arg) => { return 0; });
Promise.then(arg => { return 0; });
```

**Comment by trullock** [comment]
This looks related to #86

**Comment by stefanloerwald** [comment]
Thanks! Looking forward to the next release

**Comment by rochapablo** [comment]
I'm still getting this error Object reference not set to an instance of an object. `Uglify.Js(res)`

**Comment by trullock** [comment]
Can you open a new issue with your new input, output and expected output please
